const gui = {
    "kor": {
        "search": "\uac80\uc0c9",
        "print": "\uc120\ud0dd\ub41c \uc5b8\uc5b4\ub85c \ucd9c\ub825",
        "item": "\uc544\uc774\ud15c",
        "ability": "\ud2b9\uc131",
        "teratype": "\ud14c\ub77c\uc2a4\ud0c8\ud0c0\uc785",
        "cpoke": "\ud3ec\ucf13\ubaac \uc120\ud0dd",
        "cability": "\ud2b9\uc131 \uc120\ud0dd",
        "citem": "\uc544\uc774\ud15c \uc120\ud0dd",
        "ctera": "\ud14c\ub77c\uc2a4\ud0c8\ud0c0\uc785 \uc120\ud0dd",
        "cmove": "\uae30\uc220 \uc120\ud0dd",
        "tourname": "\ub300\ud68c \uc774\ub984",
        "playername": "\uc120\uc218\uba85",
        "comments": "\ucd94\uac00\uc0ac\ud56d \uae30\uc7ac(\uc120\ud0dd)",
        "comment": "\ucd94\uac00\uc0ac\ud56d \uae30\uc7ac",
        "chs": "\uc911\uad6d\uc5b4 \uac04\uccb4",
        "cht": "\uc911\uad6d\uc5b4 \ubc88\uccb4",
        "jpn": "\uc77c\ubcf8\uc5b4",
        "jpn_kanji": "\uc77c\ubcf8\uc5b4 \ud55c\uc790",
        "kor": "\ud55c\uad6d\uc5b4",
        "ger": "\ub3c5\uc77c\uc5b4",
        "en": "\uc601\uc5b4",
        "es": "\uc2a4\ud398\uc778\uc5b4",
        "ita": "\uc774\ud0c8\ub9ac\uc544\uc5b4",
        "fre": "\ud504\ub791\uc2a4\uc5b4"
    },
    "jpn": {
        "search": "\u691c\u7d22",
        "print": "\u9078\u629e\u3055\u308c\u305f\u8a00\u8a9e\u3092\u8868\u793a",
        "item": "\u9053\u5177",
        "ability": "\u7279\u6027",
        "teratype": "\u30c6\u30e9\u30b9\u30bf\u30a4\u30d7",
        "cpoke": "\u30dd\u30b1\u30e2\u30f3\u3092\u9078\u3076",
        "cability": "\u7279\u6027\u3092\u9078\u3076",
        "citem": "\u9053\u5177\u3092\u9078\u3076",
        "ctera": "\u30c6\u30e9\u30b9\u30bf\u30a4\u30d7\u3092\u9078\u3076",
        "cmove": "\u6280\u3092\u9078\u3076",
        "tourname": "\u5927\u4f1a\u540d",
        "playername": "\u30d7\u30ec\u30a4\u30e4\u30fc\u540d",
        "comments": "\u30b3\u30e1\u30f3\u30c8(\u4efb\u610f)",
        "comment": "\u30b3\u30e1\u30f3\u30c8",
        "chs": "\u7c21\u4f53\u5b57",
        "cht": "\u7e41\u4f53\u5b57",
        "jpn": "\u306b\u307b\u3093\u3054",
        "jpn_kanji": "\u65e5\u672c\u8a9e",
        "kor": "\u97d3\u56fd\u8a9e",
        "ger": "\u30c9\u30a4\u30c4\u8a9e",
        "en": "\u82f1\u8a9e",
        "es": "\u30b9\u30da\u30a4\u30f3\u8a9e",
        "ita": "\u30a4\u30bf\u30ea\u30a2\u8a9e",
        "fre": "\u30d5\u30e9\u30f3\u30b9\u8a9e"
    },
    "jpn_kanji": {
        "search": "\u691c\u7d22",
        "print": "\u9078\u629e\u3055\u308c\u305f\u8a00\u8a9e\u3092\u8868\u793a",
        "item": "\u9053\u5177",
        "ability": "\u7279\u6027",
        "teratype": "\u30c6\u30e9\u30b9\u30bf\u30a4\u30d7",
        "cpoke": "\u30dd\u30b1\u30e2\u30f3\u3092\u9078\u3076",
        "cability": "\u7279\u6027\u3092\u9078\u3076",
        "citem": "\u9053\u5177\u3092\u9078\u3076",
        "ctera": "\u30c6\u30e9\u30b9\u30bf\u30a4\u30d7\u3092\u9078\u3076",
        "cmove": "\u6280\u3092\u9078\u3076",
        "tourname": "\u5927\u4f1a\u540d",
        "playername": "\u30d7\u30ec\u30a4\u30e4\u30fc\u540d",
        "comments": "\u30b3\u30e1\u30f3\u30c8(\u4efb\u610f)",
        "comment": "\u30b3\u30e1\u30f3\u30c8",
        "chs": "\u7c21\u4f53\u5b57",
        "cht": "\u7e41\u4f53\u5b57",
        "jpn": "\u306b\u307b\u3093\u3054",
        "jpn_kanji": "\u65e5\u672c\u8a9e",
        "kor": "\u97d3\u56fd\u8a9e",
        "ger": "\u30c9\u30a4\u30c4\u8a9e",
        "en": "\u82f1\u8a9e",
        "es": "\u30b9\u30da\u30a4\u30f3\u8a9e",
        "ita": "\u30a4\u30bf\u30ea\u30a2\u8a9e",
        "fre": "\u30d5\u30e9\u30f3\u30b9\u8a9e"
    },
    "en": {
        "search": "Search...",
        "print": "PRINT SELECTED LANGUAGES",
        "item": "Item",
        "ability": "Ability",
        "teratype": "Teratype",
        "cpoke": "Choose Pok\u00e9mon",
        "cability": "Choose Ability",
        "citem": "Choose Item",
        "ctera": "Choose Teratype",
        "cmove": "Choose Move",
        "tourname": "Tournament name",
        "playername": "Player name",
        "comments": "Comments (optional)",
        "comment": "Comments",
        "chs": "Simplified Chinese",
        "cht": "Traditional Chinese",
        "jpn": "Japanese",
        "jpn_kanji": "Japanese Kanji",
        "kor": "Korean",
        "ger": "German",
        "en": "English",
        "es": "Spanish",
        "ita": "Italian",
        "fre": "French"
    },
    "es": {
        "search": "Buscar...",
        "print": "IMPRIMIR IDIOMAS SELECCIONADOS",
        "item": "Objeto",
        "ability": "Habilidad",
        "teratype": "Teratipo",
        "cpoke": "Scegliere i Pok\u00e9mon",
        "cability": "Scegliere l'abilit\u00e0",
        "citem": "Scegliere l'articolo",
        "ctera": "Scegliere il Teratotipo",
        "cmove": "Scegliere il movimento",
        "tourname": "Nombre del torneo",
        "playername": "Nombre del Jugador",
        "comments": "Comentarios (opcional)",
        "comment": "Comentarios",
        "chs": "Chino simplificado",
        "cht": "Chino tradicional",
        "jpn": "Japon\u00e9s",
        "jpn_kanji": "Japon\u00e9s Kanji",
        "kor": "Coreano",
        "ger": "Alem\u00e1n",
        "en": "Ingl\u00e9s",
        "es": "Espa\u00f1ol",
        "ita": "Italiano",
        "fre": "Franc\u00e9s"
    },
    "ita": {
        "search": "Search...",
        "print": "PRINT SELECTED LANGUAGES",
        "item": "Item",
        "ability": "Ability",
        "teratype": "Teratype",
        "cpoke": "Choose Pok\u00e9mon",
        "cability": "Choose Ability",
        "citem": "Choose Item",
        "ctera": "Choose Teratype",
        "cmove": "Choose Move",
        "tourname": "Tournament name",
        "playername": "Player name",
        "comments": "Comments (optional)",
        "comment": "Comments",
        "chs": "Simplified Chinese",
        "cht": "Traditional Chinese",
        "jpn": "Japanese",
        "jpn_kanji": "Japanese Kanji",
        "kor": "Korean",
        "ger": "German",
        "en": "English",
        "es": "Spanish",
        "ita": "Italian",
        "fre": "French"
    },
    "ger": {
        "search": "Search...",
        "print": "PRINT SELECTED LANGUAGES",
        "item": "Item",
        "ability": "Ability",
        "teratype": "Teratype",
        "cpoke": "Choose Pok\u00e9mon",
        "cability": "Choose Ability",
        "citem": "Choose Item",
        "ctera": "Choose Teratype",
        "cmove": "Choose Move",
        "tourname": "Tournament name",
        "playername": "Player name",
        "comments": "Comments (optional)",
        "comment": "Comments",
        "chs": "Simplified Chinese",
        "cht": "Traditional Chinese",
        "jpn": "Japanese",
        "jpn_kanji": "Japanese Kanji",
        "kor": "Korean",
        "ger": "German",
        "en": "English",
        "es": "Spanish",
        "ita": "Italian",
        "fre": "French"
    },
    "fre": {
        "search": "Search...",
        "print": "PRINT SELECTED LANGUAGES",
        "item": "Item",
        "ability": "Ability",
        "teratype": "Teratype",
        "cpoke": "Choose Pok\u00e9mon",
        "cability": "Choose Ability",
        "citem": "Choose Item",
        "ctera": "Choose Teratype",
        "cmove": "Choose Move",
        "tourname": "Tournament name",
        "playername": "Player name",
        "comments": "Comments (optional)",
        "comment": "Comments",
        "chs": "Simplified Chinese",
        "cht": "Traditional Chinese",
        "jpn": "Japanese",
        "jpn_kanji": "Japanese Kanji",
        "kor": "Korean",
        "ger": "German",
        "en": "English",
        "es": "Spanish",
        "ita": "Italian",
        "fre": "French"
    },
    "cht": {
        "search": "Search...",
        "print": "PRINT SELECTED LANGUAGES",
        "item": "Item",
        "ability": "Ability",
        "teratype": "Teratype",
        "cpoke": "Choose Pok\u00e9mon",
        "cability": "Choose Ability",
        "citem": "Choose Item",
        "ctera": "Choose Teratype",
        "cmove": "Choose Move",
        "tourname": "Tournament name",
        "playername": "Player name",
        "comments": "Comments (optional)",
        "comment": "Comments",
        "chs": "Simplified Chinese",
        "cht": "Traditional Chinese",
        "jpn": "Japanese",
        "jpn_kanji": "Japanese Kanji",
        "kor": "Korean",
        "ger": "German",
        "en": "English",
        "es": "Spanish",
        "ita": "Italian",
        "fre": "French"
    },
    "chs": {
        "search": "Search...",
        "print": "PRINT SELECTED LANGUAGES",
        "item": "Item",
        "ability": "Ability",
        "teratype": "Teratype",
        "cpoke": "Choose Pok\u00e9mon",
        "cability": "Choose Ability",
        "citem": "Choose Item",
        "ctera": "Choose Teratype",
        "cmove": "Choose Move",
        "tourname": "Tournament name",
        "playername": "Player name",
        "comments": "Comments (optional)",
        "comment": "Comments",
        "chs": "Simplified Chinese",
        "cht": "Traditional Chinese",
        "jpn": "Japanese",
        "jpn_kanji": "Japanese Kanji",
        "kor": "Korean",
        "ger": "German",
        "en": "English",
        "es": "Spanish",
        "ita": "Italian",
        "fre": "French"
    }
}