var freTeras = {
    "1": "Normal",
    "2": "Combat",
    "3": "Vol",
    "4": "Poison",
    "5": "Sol",
    "6": "Roche",
    "7": "Insecte",
    "8": "Spectre",
    "9": "Acier",
    "10": "Feu",
    "11": "Eau",
    "12": "Plante",
    "13": "\u00c9lectrik",
    "14": "Psy",
    "15": "Glace",
    "16": "Dragon",
    "17": "T\u00e9n\u00e8bres",
    "18": "F\u00e9e"
}